
class OdmError(Exception):
    """ The base for errors generated by flask-boiler.
    """
    pass


class PropertyEvalError(OdmError):
    """ An error generated when getting a property from an instance
            of a model.
    """
    pass
